#!/bin/sh
#
# xencommons    Script to start DomU guest
#
# Author:       Andrii Anisov <andrii_anisov@epam.com>
#
# chkconfig: 2345 70 10
# description: Starts and stops drivers domain (DomU)
### BEGIN INIT INFO
# Provides:          guest_domu
# Required-Start:    $xenstored $xenconsoled
# Should-Start:
# Required-Stop:     $xenstored $xenconsoled
# Should-Stop:
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop DomU
# Description:       Starts and stops drivers domain (DomU)
### END INIT INFO

DOMAIN_NAME="DomU"

echo "Starting ${DOMAIN_NAME}"
